[workspace]
members = ["programs/*"]
resolver = "2"

[features]
seeds = false
skip-lint = false

[programs.localnet]
interval = "4ATtXLmT25nh447GjP9BtdWJudN8uuqcNNmawRWexfx6"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 10000

[test.validator]
rpc_port = 8897

[scripts]
test = "NODE_PATH=../frontend/node_modules node --test tests/*.cjs"
